schema_version = "1.0.0"

id = "tilegenerator"
version = "2.0.0"
name = "Tile generator"
tagline = "Pixel art spritesheet render pipeline"
maintainer = "Maurycy Kujawski, Jakub Szukała"
type = "add-on"
platforms = [
	"windows-x64",
	"linux-x64",
]
blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-3.0-or-later"
]